In [ ]:
By Rajitha

# Introduction to Numpy


In [1]:
import numpy as np
import os

### Creating ndarrays

In [2]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

In [3]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[8, 6, 9, 1],
         [3, 7, 4, 4],
         [1, 9, 9, 3]],
 
        [[1, 5, 3, 1],
         [8, 1, 5, 9],
         [7, 6, 3, 9]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [4]:
a

array([ 0.,  0.,  0.])

In [5]:
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

In [6]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
c

array([[[5, 2, 8, 6],
        [7, 6, 7, 2],
        [4, 3, 1, 4]],

       [[6, 2, 3, 9],
        [5, 8, 2, 1],
        [4, 4, 4, 7]]])

In [8]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
## Arithmetic in arrays is element wise

In [10]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [11]:
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [12]:
c = a-b
c

array([20, 29, 38, 47])

## Indexing, Slicing and Iterating

In [13]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [14]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
a[2:5]

array([ 4,  9, 16], dtype=int32)

In [16]:
b = np.random.randint(1,100,(4,4))

In [17]:
b

array([[95, 56, 95, 39],
       [10, 84, 58, 90],
       [66, 22, 53, 99],
       [82, 58,  2, 56]])

In [18]:
# Guess the output
print(b[2,3])
print(b[0,0])


99
95


In [19]:
b[0:3,1],b[:,1]

(array([56, 84, 22]), array([56, 84, 22, 58]))

In [20]:
b[1:3,:]

array([[10, 84, 58, 90],
       [66, 22, 53, 99]])

In [21]:
b**2

array([[9025, 3136, 9025, 1521],
       [ 100, 7056, 3364, 8100],
       [4356,  484, 2809, 9801],
       [6724, 3364,    4, 3136]], dtype=int32)

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [24]:
np.random.rand(4,6)


array([[ 0.84991199,  0.31850081,  0.82536377,  0.82309992,  0.13105095,
         0.5531881 ],
       [ 0.10268788,  0.96387834,  0.09705453,  0.39303054,  0.610111  ,
         0.70997286],
       [ 0.94042114,  0.73356419,  0.75596633,  0.56083982,  0.10681835,
         0.64420668],
       [ 0.28037293,  0.79117581,  0.32501503,  0.81649349,  0.85339907,
         0.87268397]])

In [25]:
df = pd.DataFrame(np.random.rand(6,4),index=dates,columns=list('ABCD'))
df


A         B         C         D
2014-01-01  0.907913  0.109860  0.124130  0.027429
2014-01-02  0.986940  0.531949  0.764955  0.487257
2014-01-03  0.304045  0.752759  0.178165  0.373088
2014-01-04  0.160312  0.918422  0.005967  0.241819
2014-01-05  0.135583  0.440466  0.551191  0.627322
2014-01-06  0.720554  0.787659  0.298976  0.693232

In [26]:
z = pd.DataFrame(index = df.index, columns = df.columns)

In [27]:
z.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [28]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.535891  0.590186  0.320564  0.408358
std    0.382362  0.293150  0.285998  0.248761
min    0.135583  0.109860  0.005967  0.027429
25%    0.196246  0.463337  0.137639  0.274636
50%    0.512300  0.642354  0.238571  0.430172
75%    0.861073  0.778934  0.488137  0.592306
max    0.986940  0.918422  0.764955  0.693232

##### df.T
df

In [29]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [30]:
# With specific dtypes
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

#### Viewing Data

In [31]:
df.head()

A         B         C         D
2014-01-01  0.907913  0.109860  0.124130  0.027429
2014-01-02  0.986940  0.531949  0.764955  0.487257
2014-01-03  0.304045  0.752759  0.178165  0.373088
2014-01-04  0.160312  0.918422  0.005967  0.241819
2014-01-05  0.135583  0.440466  0.551191  0.627322

In [32]:
df.tail()

A         B         C         D
2014-01-02  0.986940  0.531949  0.764955  0.487257
2014-01-03  0.304045  0.752759  0.178165  0.373088
2014-01-04  0.160312  0.918422  0.005967  0.241819
2014-01-05  0.135583  0.440466  0.551191  0.627322
2014-01-06  0.720554  0.787659  0.298976  0.693232

In [33]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [34]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.535891  0.590186  0.320564  0.408358
std    0.382362  0.293150  0.285998  0.248761
min    0.135583  0.109860  0.005967  0.027429
25%    0.196246  0.463337  0.137639  0.274636
50%    0.512300  0.642354  0.238571  0.430172
75%    0.861073  0.778934  0.488137  0.592306
max    0.986940  0.918422  0.764955  0.693232

In [35]:
df.sort_values(by='B')
df #without

A         B         C         D
2014-01-01  0.907913  0.109860  0.124130  0.027429
2014-01-02  0.986940  0.531949  0.764955  0.487257
2014-01-03  0.304045  0.752759  0.178165  0.373088
2014-01-04  0.160312  0.918422  0.005967  0.241819
2014-01-05  0.135583  0.440466  0.551191  0.627322
2014-01-06  0.720554  0.787659  0.298976  0.693232

### Selection

In [36]:
df[['A','B']]

A         B
2014-01-01  0.907913  0.109860
2014-01-02  0.986940  0.531949
2014-01-03  0.304045  0.752759
2014-01-04  0.160312  0.918422
2014-01-05  0.135583  0.440466
2014-01-06  0.720554  0.787659

In [37]:
df[0:3]

A         B         C         D
2014-01-01  0.907913  0.109860  0.124130  0.027429
2014-01-02  0.986940  0.531949  0.764955  0.487257
2014-01-03  0.304045  0.752759  0.178165  0.373088

In [38]:
# By label
df.loc[dates[0]]

A    0.907913
B    0.109860
C    0.124130
D    0.027429
Name: 2014-01-01 00:00:00, dtype: float64

In [39]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  0.907913  0.109860
2014-01-02  0.986940  0.531949
2014-01-03  0.304045  0.752759
2014-01-04  0.160312  0.918422
2014-01-05  0.135583  0.440466
2014-01-06  0.720554  0.787659

In [40]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  0.531949
2014-01-03  0.752759
2014-01-04  0.918422

In [41]:
# Fast access to scalar
df.at[dates[1],'B']

0.53194920275586266

In [42]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04  0.160312  0.918422  0.005967  0.241819
2014-01-05  0.135583  0.440466  0.551191  0.627322
2014-01-06  0.720554  0.787659  0.298976  0.693232

In [43]:
df.A < 0

2014-01-01    False
2014-01-02    False
2014-01-03    False
2014-01-04    False
2014-01-05    False
2014-01-06    False
Freq: D, Name: A, dtype: bool

### Boolean Indexing

In [44]:
df[df.A < 0] # Basically a 'where' operation

Empty DataFrame
Columns: [A, B, C, D]
Index: []

### Setting

In [45]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [46]:
df_posA

A         B         C         D
2014-01-01  0.907913  0.109860  0.124130  0.027429
2014-01-02  0.986940  0.531949  0.764955  0.487257
2014-01-03  0.304045  0.752759  0.178165  0.373088
2014-01-04  0.160312  0.918422  0.005967  0.241819
2014-01-05  0.135583  0.440466  0.551191  0.627322
2014-01-06  0.720554  0.787659  0.298976  0.693232

In [47]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [48]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [49]:
df['F'] = s1

In [50]:
df

A         B         C         D    F
2014-01-01  0.907913  0.109860  0.124130  0.027429  NaN
2014-01-02  0.986940  0.531949  0.764955  0.487257  1.0
2014-01-03  0.304045  0.752759  0.178165  0.373088  2.0
2014-01-04  0.160312  0.918422  0.005967  0.241819  3.0
2014-01-05  0.135583  0.440466  0.551191  0.627322  4.0
2014-01-06  0.720554  0.787659  0.298976  0.693232  5.0

### Missing Data

In [51]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [52]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [53]:
df1

A         B         C         D    F    E
2014-01-01  0.907913  0.109860  0.124130  0.027429  NaN  1.0
2014-01-02  0.986940  0.531949  0.764955  0.487257  1.0  1.0
2014-01-03  0.304045  0.752759  0.178165  0.373088  2.0  NaN
2014-01-04  0.160312  0.918422  0.005967  0.241819  3.0  NaN

In [54]:
# find where values are null
pd.isnull(df)

A      B      C      D      F
2014-01-01  False  False  False  False   True
2014-01-02  False  False  False  False  False
2014-01-03  False  False  False  False  False
2014-01-04  False  False  False  False  False
2014-01-05  False  False  False  False  False
2014-01-06  False  False  False  False  False

### Operations

In [55]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean   0.535891  0.590186  0.320564  0.408358  3.000000
std    0.382362  0.293150  0.285998  0.248761  1.581139
min    0.135583  0.109860  0.005967  0.027429  1.000000
25%    0.196246  0.463337  0.137639  0.274636  2.000000
50%    0.512300  0.642354  0.238571  0.430172  3.000000
75%    0.861073  0.778934  0.488137  0.592306  4.000000
max    0.986940  0.918422  0.764955  0.693232  5.000000

In [56]:
df.mean() # Operation on dataframe

A    0.535891
B    0.590186
C    0.320564
D    0.408358
F    3.000000
dtype: float64

In [57]:
df.mean(),df.mean(1) # Operation on two different axes

(A    0.535891
 B    0.590186
 C    0.320564
 D    0.408358
 F    3.000000
 dtype: float64, 2014-01-01    0.292333
 2014-01-02    0.754220
 2014-01-03    0.721611
 2014-01-04    0.865304
 2014-01-05    1.150913
 2014-01-06    1.500084
 Freq: D, dtype: float64)

### Applying functions

In [58]:
df

A         B         C         D    F
2014-01-01  0.907913  0.109860  0.124130  0.027429  NaN
2014-01-02  0.986940  0.531949  0.764955  0.487257  1.0
2014-01-03  0.304045  0.752759  0.178165  0.373088  2.0
2014-01-04  0.160312  0.918422  0.005967  0.241819  3.0
2014-01-05  0.135583  0.440466  0.551191  0.627322  4.0
2014-01-06  0.720554  0.787659  0.298976  0.693232  5.0

In [59]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  0.907913  0.109860  0.124130  0.027429   NaN
2014-01-02  1.894852  0.641809  0.889085  0.514686   1.0
2014-01-03  2.198897  1.394568  1.067250  0.887774   3.0
2014-01-04  2.359210  2.312990  1.073217  1.129593   6.0
2014-01-05  2.494793  2.753456  1.624408  1.756915  10.0
2014-01-06  3.215347  3.541115  1.923385  2.450147  15.0

[Python Lambda](http://www.secnetix.de/olli/Python/lambda_functions.hawk)

In [60]:
df.apply(lambda x: x.max() - x.min())


A    0.851356
B    0.808561
C    0.758988
D    0.665803
F    4.000000
dtype: float64

In [61]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [62]:
np.random.rand(10,4)

array([[ 0.79380531,  0.20463189,  0.86157777,  0.09902328],
       [ 0.69101449,  0.10676233,  0.57728998,  0.34252681],
       [ 0.56693521,  0.5464805 ,  0.71632845,  0.62442694],
       [ 0.44976667,  0.21421136,  0.23120162,  0.19080402],
       [ 0.85346914,  0.62316951,  0.27913644,  0.90187774],
       [ 0.98286906,  0.44196201,  0.66323496,  0.93644303],
       [ 0.83160259,  0.26812498,  0.46130424,  0.68472847],
       [ 0.50551076,  0.76913627,  0.46103224,  0.21219502],
       [ 0.44189615,  0.97538609,  0.57211871,  0.77327105],
       [ 0.36832847,  0.71400243,  0.73484382,  0.35659502]])

In [63]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(6,4))
df

0         1         2         3
0  1.763378 -1.068123  0.395315  0.757799
1 -0.945802  0.742853  0.563190 -0.850273
2 -0.942363 -1.056539 -0.200700  0.498577
3 -1.438856 -1.663928  0.276393  1.596997
4 -0.654965  1.190594  0.160078 -0.459180
5 -2.547377  0.512479 -1.578932  0.608410

In [64]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0  1.763378 -1.068123  0.395315  0.757799
 1 -0.945802  0.742853  0.563190 -0.850273
 2 -0.942363 -1.056539 -0.200700  0.498577,
           0         1         2         3
 3 -1.438856 -1.663928  0.276393  1.596997
 4 -0.654965  1.190594  0.160078 -0.459180
 5 -2.547377  0.512479 -1.578932  0.608410,
 Empty DataFrame
 Columns: [0, 1, 2, 3]
 Index: []]

In [65]:
pd.concat(pieces)

0         1         2         3
0  1.763378 -1.068123  0.395315  0.757799
1 -0.945802  0.742853  0.563190 -0.850273
2 -0.942363 -1.056539 -0.200700  0.498577
3 -1.438856 -1.663928  0.276393  1.596997
4 -0.654965  1.190594  0.160078 -0.459180
5 -2.547377  0.512479 -1.578932  0.608410

In [66]:
# Also can "Join" and "Append"
df

0         1         2         3
0  1.763378 -1.068123  0.395315  0.757799
1 -0.945802  0.742853  0.563190 -0.850273
2 -0.942363 -1.056539 -0.200700  0.498577
3 -1.438856 -1.663928  0.276393  1.596997
4 -0.654965  1.190594  0.160078 -0.459180
5 -2.547377  0.512479 -1.578932  0.608410

### Grouping


In [67]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [68]:
df

A      B         C         D
0  foo    one  0.247413 -0.170931
1  bar    one -0.075787 -1.644676
2  foo    two  1.551202 -0.815308
3  bar  three -3.149702 -0.566684
4  foo    two  0.551211  0.885242
5  bar    two  0.530331  0.177042
6  foo    one -0.117616 -1.024469
7  foo  three  0.503298  0.016172

In [69]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -0.075787 -1.644676
    three -3.149702 -0.566684
    two    0.530331  0.177042
foo one    0.129797 -1.195400
    three  0.503298  0.016172
    two    2.102414  0.069934

### Reshaping

In [70]:
a = df.groupby(['A','B']).sum()

In [71]:
a

C         D
A   B                        
bar one   -0.075787 -1.644676
    three -3.149702 -0.566684
    two    0.530331  0.177042
foo one    0.129797 -1.195400
    three  0.503298  0.016172
    two    2.102414  0.069934

In [72]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -0.075787 -3.149702  0.530331 -1.644676 -0.566684  0.177042
foo  0.064899  0.503298  1.051207 -0.597700  0.016172  0.034967

### Time Series


In [73]:
import pandas as pd
import numpy as np

In [74]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [75]:
type(rng)

pandas.core.indexes.datetimes.DatetimeIndex

In [76]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [77]:
ts

2014-01-01 00:00:00     88
2014-01-01 00:00:01     31
2014-01-01 00:00:02    244
2014-01-01 00:00:03    184
2014-01-01 00:00:04     93
2014-01-01 00:00:05     71
2014-01-01 00:00:06    199
2014-01-01 00:00:07    218
2014-01-01 00:00:08    365
2014-01-01 00:00:09    238
2014-01-01 00:00:10    231
2014-01-01 00:00:11    274
2014-01-01 00:00:12     65
2014-01-01 00:00:13     20
2014-01-01 00:00:14    497
2014-01-01 00:00:15     60
2014-01-01 00:00:16    228
2014-01-01 00:00:17    189
2014-01-01 00:00:18    230
2014-01-01 00:00:19    254
2014-01-01 00:00:20     35
2014-01-01 00:00:21    394
2014-01-01 00:00:22    100
2014-01-01 00:00:23     90
2014-01-01 00:00:24    226
2014-01-01 00:00:25    183
2014-01-01 00:00:26     83
2014-01-01 00:00:27     73
2014-01-01 00:00:28    224
2014-01-01 00:00:29    131
                      ... 
2014-01-01 00:01:10    440
2014-01-01 00:01:11     59
2014-01-01 00:01:12    109
2014-01-01 00:01:13    336
2014-01-01 00:01:14    272
2014-01-01 00:01:15    353
2

In [78]:
ts.to_csv("time.csv")

In [79]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    198.95
2014-01-01 00:01:00    261.35
Freq: T, dtype: float64

In [80]:
ts[0:60].mean()

198.95

In [81]:
ts[60:120].mean()

261.35

### Plotting


[Matplotlib Plotting Library](https://matplotlib.org/api/pyplot_api.html)

In [82]:
ts.plot()

In [83]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [84]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [85]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])


In [86]:
df = df.cumsum()


In [87]:
plt.figure();df.plot();plt.legend(loc='best') 

In [88]:
df

A          B          C         D
2014-01-01 00:00:00  0.316148   1.351923   0.953656  0.607352
2014-01-01 00:00:01  2.158918   0.382623  -0.045704 -1.062068
2014-01-01 00:00:02  1.933880  -0.275201  -1.188611  0.302005
2014-01-01 00:00:03  1.844178  -0.484778  -0.318013  0.327053
2014-01-01 00:00:04  0.693770   0.145062   0.263832 -0.102207
2014-01-01 00:00:05  1.255400  -1.099201  -1.074276  1.061648
2014-01-01 00:00:06  0.833814   0.097824  -0.581984  0.547222
2014-01-01 00:00:07  0.552168  -0.645818   0.132593 -1.380120
2014-01-01 00:00:08  0.075099   0.017304   1.580995 -2.273786
2014-01-01 00:00:09  0.025328   0.935374   1.630822 -2.808814
2014-01-01 00:00:10  0.973045   1.488113   0.701289 -5.314612
2014-01-01 00:00:11  2.568108   2.474834  -0.343281 -4.020105
2014-01-01 00:00:12  0.555363   4.038836  -0.070698 -3.594427
2014-01-01 00:00:13  0.635479   4.793598  -1.214170 -3.250161
2014-01-01 00:00:14  1.445151   4.489294  -3.377278 -3.077521
2014-01-01 00:00:15  0.566344   3.900526  -5.106396 -2.573498
2014-01-01 00:00:16  0.146260   4.159849  -6.099297 -4.545115
2014-01-01 00:00:17  0.282109   3.261869  -5.179608 -4.379475
2014-01-01 00:00:18  0.226004   3.696108  -6.980166 -2.991882
2014-01-01 00:00:19 -0.649922   3.864426  -8.387141 -3.995865
2014-01-01 00:00:20  0.461110   4.914383  -8.168653 -3.011763
2014-01-01 00:00:21  0.817666   5.470786  -7.003188 -4.693639
2014-01-01 00:00:22  0.347718   5.345202  -5.749125 -6.454323
2014-01-01 00:00:23  0.259014   4.465994  -6.128388 -6.918890
2014-01-01 00:00:24  0.211431   3.722498  -6.395273 -6.912452
2014-01-01 00:00:25 -1.329545   4.448354  -7.288977 -7.630007
2014-01-01 00:00:26 -0.301581   3.817547  -8.714641 -8.270200
2014-01-01 00:00:27 -0.182047   4.272175  -9.822430 -7.259779
2014-01-01 00:00:28  0.669028   5.510016  -9.077603 -7.283780
2014-01-01 00:00:29  0.190851   6.625268  -9.806038 -7.589718
...                       ...        ...        ...       ...
2014-01-01 00:01:10 -1.099253  23.806239 -17.972603 -9.622615
2014-01-01 00:01:11 -1.801070  24.245840 -17.170329 -8.324205
2014-01-01 00:01:12 -0.649299  22.587725 -18.202163 -7.227441
2014-01-01 00:01:13 -0.120482  21.866363 -19.023486 -7.428751
2014-01-01 00:01:14 -0.225669  21.214737 -19.200691 -6.525287
2014-01-01 00:01:15  0.523176  20.832109 -18.231744 -6.730838
2014-01-01 00:01:16  0.890882  21.852193 -17.315663 -6.996150
2014-01-01 00:01:17  0.567013  20.973539 -17.627872 -5.853894
2014-01-01 00:01:18  0.784512  20.269417 -17.076771 -6.717341
2014-01-01 00:01:19  0.987399  20.914321 -18.562753 -5.531724
2014-01-01 00:01:20  0.944016  20.029713 -18.317147 -4.991254
2014-01-01 00:01:21  1.841227  18.971578 -18.310132 -5.538261
2014-01-01 00:01:22  1.858276  19.517580 -17.886010 -4.971945
2014-01-01 00:01:23  0.730666  17.753030 -18.608155 -4.501236
2014-01-01 00:01:24  1.317462  17.166746 -19.716965 -5.749861
2014-01-01 00:01:25  0.913054  17.810540 -18.509519 -6.881009
2014-01-01 00:01:26 -0.813199  16.804978 -19.093119 -6.890336
2014-01-01 00:01:27 -0.413717  15.434100 -19.613792 -6.844886
2014-01-01 00:01:28  0.385883  16.800732 -18.937582 -6.164244
2014-01-01 00:01:29  1.127012  16.982353 -18.363626 -6.139685
2014-01-01 00:01:30  0.489778  17.006131 -16.318047 -7.498103
2014-01-01 00:01:31 -0.924797  16.523848 -16.547665 -5.647154
2014-01-01 00:01:32  0.313445  17.130698 -16.882435 -6.856516
2014-01-01 00:01:33 -1.043743  18.426577 -16.176658 -6.290704
2014-01-01 00:01:34 -1.953763  18.944566 -17.172764 -6.711394
2014-01-01 00:01:35 -2.143802  18.971684 -19.535873 -6.026821
2014-01-01 00:01:36 -3.415739  19.578721 -20.246488 -5.837508
2014-01-01 00:01:37 -5.332234  19.772734 -21.494261 -5.040381
2014-01-01 00:01:38 -5.107387  20.051551 -20.869112 -4.158229
2014-01-01 00:01:39 -5.464812  18.700573 -22.279345 -4.553152

[100 rows x 4 columns]